version: '3'

services:
    backend:
        image: vladthesav/gpt2_onion_generator_api:api
        expose: 
            - 3500
        ports:
            - 3500:3500
        #volumes: ./backend:/app

    frontend:
        image: vladthesav/gpt2_onion_generator_frontend:latest
        expose:
            - 3000
        ports:
            - 3000:3000

        depends_on: 
            - backend